# docker-compose.yml
version: '3.0'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PSQL_HOST: db
      PSQL_USERNAME: postgres
      PSQL_PASSWORD: password